# Generated by Django 5.1.4 on 2025-01-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
