# Generated by Django 5.1.4 on 2025-01-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0002_alter_bootcamp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koder',
            name='first_name',
            field=models.CharField(max_length=254),
        ),
    ]
