# Generated by Django 5.1.4 on 2025-01-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0003_alter_koder_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koder',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='koder',
            name='update_at',
        ),
    ]
